name: Swift

on:
  push:
    branches: [ main ]

jobs:
  tests:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and test
      run: |
        xcodebuild clean test \
          -workspace MusicPractice.xcworkspace \
          -scheme MusicPractice \
          -destination 'platform=iOS Simulator,name=iPhone 11' \
          CODE_SIGNING_REQUIRED=NO
